### ISSUE TITLE
Duplicate post displayed

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#101]
### Steps to reproduce:

1)Navigate to the following page: https://planetcassandra.org/
2)Click at "Events" at the top of the page and then select "Events"
3)Scroll downwards till August 23 events

### Actual Results:
Duplicate post is displayed

### Expected Results:
The event should be posted once 

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/244299589-ad5b3ccf-e9be-459e-807e-0879def55504.png)

**Comment by andrejhristovski** [comment]
This is for Vladimir

**Comment by StojanJovanov** [comment]
@vladanee
