### ISSUE TITLE
Misalignment text below the first sentence

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#103]
### Steps to reproduce:

1. Navigate to the following page: https://planetcassandra.org/
2. Scroll at the bottom of the page

### Actual Results:
The text is deployed different 

### Expected Results:
The text should start from the same vertical line as the first sentence

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/243978018-93e669e2-a173-45f1-b506-3dc2090ed267.png)

**Comment by JovanTanchevski** [comment]
Currently working on this issue

**Comment by JovanTanchevski** [comment]
This issue has been resolved with justify
