### ISSUE TITLE
Insufficient space between the text

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#106]
### Steps to reproduce:

1)Navigate to the following page: https://planetcassandra.org/
2)Click at "News" at the top of the page
3)Click at "Apache Cassandra for the SQL Server Developer" hyperlink
4)After you are navigated to the following page https://planetcassandra.org/news/apache-cassandra-for-the-sql-server-developer/ scroll downwards exactly at the middle of the page 

### Actual Results:
There is not enough space between the text 

### Expected Results:
The text should have appropriate spacing

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/244318111-bd7673e2-f628-4b69-83a9-881d33d73f58.png)

**Comment by JovanTanchevski** [comment]
Currently working on this, resolved via table in singlePageTemplate.css
