### ISSUE TITLE
Misaligned placement of text uploaded from SQL table

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#107]
### Steps to reproduce:

1)Navigate to the following page: https://planetcassandra.org/
2)Click at "Posts" button at the top of the page
3)Click at the hyperlink named "Best Practices for Optimal Performance" 
4)After you are navigated at the following page https://planetcassandra.org/post/best-practices-for-optimal-performance/  scroll downwards 

### Actual Results:
The text scrambled
### Expected Results:
The text should be subordinate visually good looking

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/244681519-e5461f40-af33-42b5-88bd-730b66965dbb.png)

**Comment by JovanTanchevski** [comment]
Working on this issue at the moment, resolving it by trying to implement a smaller font size
