### ISSUE TITLE
"Contact us" input values  accepting Invalid data types

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#63]
### Steps to reproduce:

1. Navigate to the following page: https://planetcassandra.org/
2. Click "Contact" button on the right corner at the top of the page 
3. Fill all inputs with integers/special characters 
4. Click "Submit"

### Actual Results:
Invalid invite message is shown

### Expected Results:
The user should be  Invited successfully

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

### Recommended Solution:
- Input fields like Name, Surname, etc. should be restricted to accept varchar inputs.
- Input fields like Data, Age should be restricted to accept integer inputs.
- Message to be mandatory input also

![Image](https://user-images.githubusercontent.com/135216801/243635242-1dcc7e57-a749-4c60-aaa9-9d31a6fcba0f.jpg)
![Image](https://user-images.githubusercontent.com/135216801/243635241-b48d6f98-cb3d-46ab-9991-7bb650612582.jpg)
![Image](https://user-images.githubusercontent.com/135216801/243635243-6ff662ae-fdf2-4332-8ebd-20252fa33e53.png)

**Comment by JovanTanchevski** [comment]
Name should contain only string

**Comment by JovanTanchevski** [comment]
Note - there is NOT a regex for the form inputs

**Comment by StojanJovanov** [comment]
Issue fixed.
First Name input-Only letters allowed
Last Name input-Only letters allowed
e-mail-mandatory input
Phone number input-not mandatory(only numbers allowed)
Message-not mandatory
