### ISSUE TITLE
Inability to change month and day data when clicked

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#66]
### Steps to reproduce:

1. Navigate to the following page: https://planetcassandra.org/
2. Click "Events" at the top of the page and select "Events"
3. Click "Month" or "Day"

### Actual Results:
Data is not changing related to months or days

### Expected Results:
Data should be changed

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/243697907-4b67397e-89a8-49b3-98b3-d259cc7c4a84.png)

**Comment by andrejhristovski** [comment]
This is for Vladimir

**Comment by StojanJovanov** [comment]
@vladanee
