### ISSUE TITLE
Error message is shown after hyperlink is clicked

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#67]
### Steps to reproduce:

1. Navigate to the following page: https://planetcassandra.org/
2. Click "Use Cases" at the top of the page 
3. Click at "Bosch" hyperlink 

### Actual Results:
Error message is shown

### Expected Results:
Content should be displayed

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/245061184-4563f0e8-4d32-4eb9-b1fd-bbfa8f7bdf9a.jpg)

**Comment by JovanTanchevski** [comment]
After inspecting this element, i come to the conclusion that there is only one **_Bosch Use Case_** and at this moment it's fully functioning and working correct. * (pictures below)

![Image](https://github.com/Anant-Macedonia/anantMK/assets/101511857/fcd500ee-da63-47ac-ad1d-808a834b974a)



![Image](https://github.com/Anant-Macedonia/anantMK/assets/101511857/19b6f897-ba11-4ccf-b775-a18a09b1fdba)
