### ISSUE TITLE
Site cant be reached after "large" is clicked

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#75]
### Steps to reproduce:

1)Navigate to the following page: https://planetcassandra.org/
2)Click at "Resources" button at the top of the page
3)Click at the hyperlink named "Facebook’s Cassandra paper, annotated and compared to Apache Cassandra 2.0" 
4)After you are navigated at the following page https://planetcassandra.org/leaf/facebook-s-cassandra-paper-annotated-and-compared-to-apache-cassandra-2-0/  scroll down
5)Click at the hyperlink "large" 

### Actual Results:
Error message is shown
### Expected Results:
Respective data is shown
### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/246064935-a705ecf7-786c-4ede-a860-149c215282bc.jpg)

**Comment by JovanTanchevski** [comment]
After inspecting this problem, I came to the conclusion that at that given moment when you were inspecting this content, the page that leads from this link was down. At the moment it's fully functioning and working.

![Image](https://github.com/Anant-Macedonia/anantMK/assets/101511857/04bf3012-704f-4766-9479-cd8d3e50537c)
