### ISSUE TITLE
Picture failed to upload successfully

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#82]
### Steps to reproduce:

1)Navigate to the following page: https://planetcassandra.org/
2)Click at "Posts" button at the top of the page
3)Click at the first hyperlink named "Architect’s Guide to Using NoSQL for Real-time AI: Part 1" 
4)After you are navigated at the following page https://planetcassandra.org/post/architects-guide-to-using-nosql-for-real-time-ai-part-1/ scroll downwards almost at the middle of the page 

### Actual Results:
The picture is partly shown 

### Expected Results:
The picture should be uploaded successful 

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/244676679-bc789d02-984d-4d76-9499-87c91e50b657.png)

**Comment by JovanTanchevski** [comment]
@StojanJovanov this is from innerHTMLContent, we only get the data and place the content there
