### ISSUE TITLE
Partly shown picture at hyperlink logo BlaBlaCar

### ISSUE THREAD

**Issue by StojanJovanov** [Anant-Macedonia/anantMK#83]
### Steps to reproduce:

1)Navigate to the following page: https://planetcassandra.org/
2)Click at "Use Cases" button at the top of the page
3)Click at the hyperlink named "Bla Bla Car" 
4)After you are navigated at the following page https://planetcassandra.org/usecases/bla-bla-car/372/ observe the logo

### Actual Results:
The image is shown partly
### Expected Results:
The image should be shown fully

### Environment
OS:  Windows 10 Pro 64-bit
Browser: Brave[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)]

![Image](https://user-images.githubusercontent.com/135216801/245058840-414ae225-15b8-4c50-bfe6-aa192ee6ca41.png)

**Comment by JovanTanchevski** [comment]
@StojanJovanov  This issue has been resolved with the latest push to QA
